---
- hosts: all
  become: yes
  tasks:
  - name: install git tree and apt
    apt:
     name: git
     state: present

  - name: install tree
    apt:
     name: tree
     state: present  

  - name: install apt
    apt:
     name: apt
     state: present   